drop DATABASE if exists Lily_Undon;
CREATE DATABASE Lily_Undon;
USE Lily_Undon;

Create Table AccessLevel(
  AccessLevelID int primary key AUTO_INCREMENT,
  level varchar(50)
);
insert into AccessLevel (level) values ("Admin");
insert into AccessLevel (level) values ("SecurityGuard");
insert into AccessLevel (level) values ("Residence");



CREATE TABLE users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    First_name VARCHAR(255),
    Last_name VARCHAR(255),
    social_security_number BIGINT NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    AccessLevelID int NOT NULL,
    status BOOLEAN,
    user_must_change_password BOOLEAN,
    /* Zero is considered as false, nonzero values are considered as true. */
    FOREIGN KEY (AccessLevelID) REFERENCES AccessLevel(AccessLevelID) 
);

 create table if not exists Sites(
    SiteId INT PRIMARY KEY AUTO_INCREMENT,
    SiteName VARCHAR(255)
 );

CREATE TABLE IF NOT EXISTS reservation (
    ReservationID INT PRIMARY KEY AUTO_INCREMENT,
    Reserved_by_userID INT,
    StartMoment DATETIME,
    SiteId INT not null,
    FOREIGN KEY (Reserved_by_userID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (SiteId) REFERENCES Sites(SiteId) 
);

insert into Sites(SiteName) values("LilyUnden");
insert into Sites(SiteName) values("DonBosco");


CREATE TABLE translation (
    translationID VARCHAR(99) PRIMARY KEY,
    en VARCHAR(999),
    fr VARCHAR(999),
    de VARCHAR(999),
    ti VARCHAR(999),
    es VARCHAR(999),
    ar VARCHAR(999),
    fa VARCHAR(999)
);
INSERT INTO translation (translationID, en, fr, de, ti, es, ar, fa) VALUES
('cns_username_error', 
  'Error: The CNS number or username has already been used. Please enter a unique value.', 
  'Erreur : Le numéro CNS ou le nom d/utilisateur a déjà été utilisé. Veuillez saisir une valeur unique.', 
  'Fehler: Die CNS-Nummer oder der Benutzername wurde bereits verwendet. Bitte geben Sie einen eindeutigen Wert ein.',
  'ሓጋጊ: CNS ቑፅሪ ወይ ስም ተጠቃሚ ካብ ቅድሚ ሕጂ ተጠቒሙ ኣሎ። ብልሽው ዋጋ ኣእትዉ።',
  'Error: El número CNS o nombre de usuario ya ha sido utilizado. Por favor ingrese un valor único.',
  'خطأ: رقم CNS أو اسم المستخدم قد تم استخدامه بالفعل. يرجى إدخال قيمة فريدة.',
  'خطا: شماره CNS یا نام کاربری قبلا استفاده شده است. لطفاً یک مقدار منحصر به فرد وارد کنید.'
),
('by', 
  'by', 
  'par', 
  'von',
  'ብሓደ',
  'por',
  'بواسطة',
  'توسط'
),
('status', 
  'Status', 
  'Statut', 
  'Status',
  'ኩነት',
  'Estado',
  'الحالة',
  'وضعیت'
),
('print', 
 'Print',      
 'Imprimer',  
 'Drucken',    
 'ኣታት',         
 'Imprimir',       
 'طباعة',           
 'چاپ'              
),
('plan', 
  'Plan', 
  'Plan', 
  'Plan',
  'መደብ',
  'Plan',
  'خطة',
  'برنامه'
),
('you', 
  'You', 
  'Vous', 
  'Sie', 
  'አንተ/እርስዎ', 
  'Usted', 
  'أنت', 
  'شما'
),
('site', 
  'Site', 
  'Site', 
  'Ort', 
  'ቦታ', 
  'Sitio', 
  'موقع', 
  'مکان'
),
('login', 
  'Login', 
  'Connexion', 
  'Anmeldung',
  'እቶ',
  'Iniciar sesión',
  'تسجيل الدخول',
  'ورود'
),
('resident', 
  'Resident', 
  'Résident', 
  'Bewohner',
  'ተወላጅ',
  'Residente',
  'المقيم',
  'ساکن'
),
('security_guard', 
  'Security Guard', 
  'Agent de sécurité', 
  'Sicherheitsbeamter',
  'ዋሓዚ መድሓኒት',
  'Guardia de seguridad',
  'حارس أمن',
  'نگهبان'
),
('user_created_successfully', 
 'User created successfully! Please be patient while an admin approves your registration.', 
 'Utilisateur créé avec succès ! Veuillez patienter pendant que l/administrateur approuve votre inscription.', 
 'Benutzer erfolgreich erstellt! Bitte haben Sie etwas Geduld, bis ein Administrator Ihre Registrierung genehmigt.',
 'ተጠቃሚ ብኽብረት ተፈጢሩ! ኣስተዳደር ምዝገባኻ ክምዘን ከሎ �ጽእዎ።',
 '¡Usuario creado con éxito! Por favor sea paciente mientras un administrador aprueba su registro.',
 'تم إنشاء المستخدم بنجاح! يرجى الانتظار حتى يوافق المسؤول على تسجيلك.',
 'کاربر با موفقیت ایجاد شد! لطفاً صبر کنید تا مدیر ثبت نام شما را تأیید کند.'
),
('user_created_successfully_admin', 
 'User created successfully!', 
 'Utilisateur créé avec succès !', 
 'Benutzer erfolgreich erstellt!',
 'ተጠቃሚ ብኽብረት ተፈጢሩ!',
 '¡Usuario creado con éxito!',
 'تم إنشاء المستخدم بنجاح!',
 'کاربر با موفقیت ایجاد شد!.'
),

('passwords_not_match', 
  'Passwords do not match!', 
  'Les mots de passe ne correspondent pas !', 
  'Die Passwörter stimmen nicht überein!',
  'ፓስዎርድ ኣይሰማምዑን!',
  '¡Las contraseñas no coinciden!',
  'كلمات المرور غير متطابقة!',
  'رمزهای عبور مطابقت ندارند!'
),
('welcome_message', 
  'Welcome to Croix-Rouge', 
  'Bienvenue à la Croix-Rouge', 
  'Willkommen bei Croix-Rouge',
  'እንቋዕ ናብ ክርዋይ-ሩጅ መጻእኩም',
  'Bienvenido a Croix-Rouge',
  'مرحبًا بكم في كروا روج',
  'به صلیب سرخ خوش آمدید'
),
('form_instruction', 
  'Please fill out the form below to complete your registration. All fields marked as required must be filled in accurately.', 
  'Veuillez remplir le formulaire ci-dessous pour compléter votre inscription. Tous les champs obligatoires doivent être remplis avec précision.', 
  'Bitte füllen Sie das untenstehende Formular aus, um Ihre Registrierung abzuschließen. Alle Pflichtfelder müssen korrekt ausgefüllt werden.',
  'በጃኹም ነቲ ታሕቲ ዘሎ ፎርም ምሉእ ብምሉእ ምዝገባኹም ንምውሳኽ መልአይ። ኩሉ ኣገዳሲ ክፍልታት ብትኽክል ክምላእ ኣለዎ።',
  'Por favor complete el formulario a continuación para completar su registro. Todos los campos marcados como obligatorios deben completarse con precisión.',
  'يرجى ملء النموذج أدناه لإكمال تسجيلك. يجب ملء جميع الحقول المطلوبة بدقة.',
  'لطفاً فرم زیر را برای تکمیل ثبت نام پر کنید. تمام فیلدهای الزامی باید به دقت پر شوند.'
),

('first_name',
  'First name', 
  'Prénom', 
  'Vorname',
  'ሽም',
  'Nombre',
  'الاسم الأول',
  'نام'
),
('last_name', 
  'Last Name', 
  'Nom de famille', 
  'Nachname',
  'ሽም ኣቦ',
  'Apellido',
  'الاسم الأخير',
  'نام خانوادگی'
),
('social_security_number', 
  'Social Security Number', 
  'Numéro de sécurité sociale', 
  'Sozialversicherungsnummer',
  'ቑፅሪ ማሕበራዊ ጸጥታ',
  'Número de Seguridad Social',
  'رقم الضمان الاجتماعي',
  'شماره تأمین اجتماعی'
),
('username', 
  'Username', 
  'Nom d/utilisateur', 
  'Benutzername',
  'ስም ተጠቃሚ',
  'Nombre de usuario',
  'اسم المستخدم',
  'نام کاربری'
),
('password', 
  'Password', 
  'Mot de passe', 
  'Passwort',
  'ፓስዎርድ',
  'Contraseña',
  'كلمة المرور',
  'رمز عبور'
),
('password_confirmation', 
  'Password Confirmation', 
  'Confirmation du mot de passe', 
  'Passwortbestätigung',
  'ምርግጋእ ፓስዎርድ',
  'Confirmación de contraseña',
  'تأكيد كلمة المرور',
  'تأیید رمز عبور'
),
('email', 
  'Email', 
  'Email', 
  'E-Mail',
  'ኢመይል',
  'Correo electrónico',
  'البريد الإلكتروني',
  'ایمیل'
),
('sign_in', 
  'Sign In', 
  'Se connecter', 
  'Anmelden',
  'እቶ',
  'Iniciar sesión',
  'تسجيل الدخول',
  'ورود'
),
('register', 
  'Register', 
  'S/inscrire', 
  'Registrieren',
  'ተመዝገብ',
  'Registrarse',
  'تسجيل',
  'ثبت نام'
),


/* index */
('home', 
  'Home', 
  'Accueil', 
  'Startseite',
  'ቤት',
  'Inicio',
  'الرئيسية',
  'خانه'
),
('cook', 
  'Cook', 
  'Cuisinier', 
  'Koch',
  'ሰበስልጣን',
  'Cocinar',
  'يطبخ',
  'آشپزی'
),
('enjoy', 
  'Enjoy', 
  'Profitez', 
  'Genießen',
  'ተደስት',
  'Disfrutar',
  'استمتع',
  'لذت ببرید'
),
('Logout', 
  'Logout', 
  'Déconnexion', 
  'Abmelden',
  'ውጻእ',
  'Cerrar sesión',
  'تسجيل الخروج',
  'خروج'
),
('Reserve', 
  'Reserve', 
  'Réserver', 
  'Reservieren',
  'ቅድም ምዝገባ',
  'Reservar',
  'حجز',
  'رزرو'
),

/* logout or in */
('login_logout', 
  'Login/Logout', 
  'Connexion/Déconnexion', 
  'Anmelden/Abmelden',
  'እቶ/ውጻእ',
  'Iniciar/Cerrar sesión',
  'تسجيل الدخول/الخروج',
  'ورود/خروج'
),
('password_incorrect', 
  'Password is incorrect!', 
  'Le mot de passe est incorrect !', 
  'Das Passwort ist falsch!',
  'ፓስዎርድ ኣይቅኑዕን እዩ!',
  '¡La contraseña es incorrecta!',
  'كلمة المرور غير صحيحة!',
  'رمز عبور نادرست است!'
),
('username_not_found', 
  'Username could not be found!', 
  'Nom d/utilisateur introuvable !', 
  'Benutzername konnte nicht gefunden werden!',
  'ስም ተጠቃሚ ኣይተረኽበን!',
  '¡Nombre de usuario no encontrado!',
  'اسم المستخدم غير موجود!',
  'نام کاربری یافت نشد!'
),
('initial_password_change_required', 
  'Your initial password needs to be changed. Please change your password and try again.', 
  'Votre mot de passe initial doit être changé. Veuillez le modifier et réessayer.', 
  'Ihr Anfangspasswort muss geändert werden. Bitte ändern Sie Ihr Passwort und versuchen Sie es erneut.',
  'እቲ ናይ መጀመርታ ፓስዎርድካ ክቕየር ኣለዎ። ፓስዎርድካ ቀይርካ መሊስ ፈትን።',
  'Su contraseña inicial debe ser cambiada. Por favor cambie su contraseña e intente nuevamente.',
  'يجب تغيير كلمة المرور الأولية الخاصة بك. يرجى تغيير كلمة المرور الخاصة بك وحاول مرة أخرى.',
  'رمز عبور اولیه شما نیاز به تغییر دارد. لطفاً رمز عبور خود را تغییر دهید و دوباره امتحان کنید.'
),
('secure_account', 
  'Secure your account. Please update your password and keep your information safe.', 
  'Sécurisez votre compte. Veuillez mettre à jour votre mot de passe et protéger vos informations.', 
  'Sichern Sie Ihr Konto. Bitte aktualisieren Sie Ihr Passwort und schützen Sie Ihre Daten.',
  'ሕሳብካ ኣስተማምዖ። ፓስዎርድካ ኣዘምንካ ሓበሬታኻ ጸጥ ኣቢልካ ኣስተምህሮ።',
  'Proteja su cuenta. Por favor actualice su contraseña y mantenga su información segura.',
  'قم بتأمين حسابك. يرجى تحديث كلمة المرور الخاصة بك والحفاظ على معلوماتك آمنة.',
  'حساب خود را ایمن کنید. لطفاً رمز عبور خود را به روز رسانی کنید و اطلاعات خود را ایمن نگه دارید.'
),
('welcome_tagline', 
  'Empowering communities with care. Please sign in to manage your reservations and services.', 
  'Autonomiser les communautés avec bienveillance. Veuillez vous connecter pour gérer vos réservations et services.', 
  'Gemeinschaften mit Fürsorge stärken. Bitte melden Sie sich an, um Ihre Reservierungen und Dienste zu verwalten.',
  'ሕብረተሰብ ብሕክምና ሓይሊ ምሃብ። ንምዝገባታትኩምን ኣገልግሎታትኩምን ንምቕዳሕ እቶ ግበሩ።',
  'Empoderando comunidades con cuidado. Por favor inicie sesión para administrar sus reservas y servicios.',
  'تمكين المجتمعات بالرعاية. يرجى تسجيل الدخول لإدارة الحجوزات والخدمات الخاصة بك.',
  'توانمندسازی جوامع با مراقبت. لطفاً برای مدیریت رزروها و خدمات خود وارد شوید.'
),
('forgot_password', 
  'Forgot Password?', 
  'Mot de passe oublié ?', 
  'Passwort vergessen?',
  'ፓስዎርድ ረሲዕኩምዶ?',
  '¿Olvidó su contraseña?',
  'نسيت كلمة المرور؟',
  'رمز عبور را فراموش کرده اید؟'
),
('or_sign_in_with', 
  'Or sign in with', 
  'Ou connectez-vous avec', 
  'Oder anmelden mit',
  'ወይ ብ',
  'O iniciar sesión con',
  'أو تسجيل الدخول باستخدام',
  'یا وارد شوید با'
),
('sign_up', 
  'Sign Up', 
  'S/inscrire', 
  'Registrieren',
  'ተመዝገብ',
  'Registrarse',
  'اشتراك',
  'ثبت نام'
),
('no_account', 
  'Don/t have an account?', 
  'Vous n/avez pas de compte ?', 
  'Sie haben noch kein Konto?',
  'ሕሳብ የብልኩምንዶ?',
  '¿No tienes una cuenta?',
  'ليس لديك حساب؟',
  'حساب کاربری ندارید؟'
),
('password_updated', 
  'Password updated successfully.', 
  'Mot de passe mis à jour avec succès.', 
  'Passwort erfolgreich aktualisiert.',
  'ፓስዎርድ ብኽብረት ኣዘምነ።',
  'Contraseña actualizada exitosamente.',
  'تم تحديث كلمة المرور بنجاح.',
  'رمز عبور با موفقیت به روز شد.'
),
('password_update_failed', 
  'Failed to update password', 
  'Échec de la mise à jour du mot de passe', 
  'Fehler beim Aktualisieren des Passworts',
  'ኣዘምነት ፓስዎርድ ኣይተሳነን።',
  'Error al actualizar la contraseña',
  'فشل تحديث كلمة المرور',
  'به روز رسانی رمز عبور ناموفق بود'
),
('new_passwords_do_not_match', 
  'New passwords do not match!', 
  'Les nouveaux mots de passe ne correspondent pas !', 
  'Die neuen Passwörter stimmen nicht überein!',
  'ሓድሽ ፓስዎርድ ኣይሰማምዑን!',
  '¡Las nuevas contraseñas no coinciden!',
  'كلمات المرور الجديدة غير متطابقة!',
  'رمزهای عبور جدید مطابقت ندارند!'
),
('current_password_incorrect', 
  'Your current password is incorrect', 
  'Votre mot de passe actuel est incorrect', 
  'Ihr aktuelles Passwort ist falsch',
  'እቲ ኣሁኑ ፓስዎርድካ ኣይቅኑዕን እዩ።',
  'Su contraseña actual es incorrecta',
  'كلمة المرور الحالية غير صحيحة',
  'رمز عبور فعلی شما نادرست است'
),
('user_not_found', 
  'User not found', 
  'Utilisateur non trouvé', 
  'Benutzer nicht gefunden',
  'ተጠቃሚ ኣይተረኽበን',
  'Usuario no encontrado',
  'المستخدم غير موجود',
  'کاربر یافت نشد'
),
('please_be_patient_while_admin_approves_your_account',
  'Please be patient while admin approves your account',
  'Veuillez patienter pendant que l\administrateur approuve votre compte',
  'Bitte haben Sie Geduld, während der Administrator Ihr Konto freigibt',
  'እባክዎን አስተዳዳሪው መለያዎን እስኪፈቅድ ይጠብቁ',
  'Por favor, tenga paciencia mientras el administrador aprueba su cuenta',
  'يرجى الانتظار حتى يقوم المدير بالموافقة على حسابك',
  'لطفاً صبر کنید تا مدیر حساب شما را تأیید کند'
),
('all_fields_required', 
  'All fields are required', 
  'Tous les champs sont obligatoires', 
  'Alle Felder sind erforderlich',
  'ኩሉ ክፍልታት ኣገዳሲ እዩ',
  'Todos los campos son obligatorios',
  'جميع الحقول مطلوبة',
  'تمامی فیلدها الزامی هستند'
),
('current_password', 
  'Current Password', 
  'Mot de passe actuel', 
  'Aktuelles Passwort',
  'ኣሁኑ ፓስዎርድ',
  'Contraseña actual',
  'كلمة المرور الحالية',
  'رمز عبور فعلی'
),
('new_password', 
  'New Password', 
  'Nouveau mot de passe', 
  'Neues Passwort',
  'ሓድሽ ፓስዎርድ',
  'Nueva contraseña',
  'كلمة المرور الجديدة',
  'رمز عبور جدید'
),
('confirm_new_password', 
  'Confirm New Password', 
  'Confirmer le nouveau mot de passe', 
  'Neues Passwort bestätigen',
  'ሓድሽ ፓስዎርድ ኣረጋግጽ',
  'Confirmar nueva contraseña',
  'تأكيد كلمة المرور الجديدة',
  'تأیید رمز عبور جدید'
),
('update_password', 
  'Update Password', 
  'Mettre à jour le mot de passe', 
  'Passwort aktualisieren',
  'ፓስዎርድ ኣዘምን',
  'Actualizar contraseña',
  'تحديث كلمة المرور',
  'به روز رسانی رمز عبور'
),
('session_terminated_status_changed', 
 'Your session has been terminated because your account status has changed. Please contact the administrator if you believe this is a mistake.', 
 'Votre session a été terminée car le statut de votre compte a changé. Veuillez contacter l/administrateur si vous pensez qu/il s/agit d/une erreur.', 
 'Ihre Sitzung wurde beendet, weil sich der Status Ihres Kontos geändert hat. Bitte kontaktieren Sie den Administrator, wenn Sie glauben, dass dies ein Fehler ist.',
 'እቲ ናይ ሕሳብኩም ስታተስ ስለዝበዝሐ እቲ ናይ ስራሕ እዋን ተቋሪጹ። እዚ ሓጋጊ ምዃኑ እንተሓስብኩም ምስ ኣስተዳደር ተራኸቡ።',
 'Su sesión ha sido terminada porque el estado de su cuenta ha cambiado. Por favor contacte al administrador si cree que esto es un error.',
 'تم إنهاء جلستك لأن حالة حسابك قد تغيرت. يرجى الاتصال بالمسؤول إذا كنت تعتقد أن هذا خطأ.',
 'جلسه شما به دلیل تغییر وضعیت حساب کاربری شما خاتمه یافته است. اگر فکر می کنید این یک اشتباه است، لطفاً با مدیر تماس بگیرید.'
),


/* my reservation */
('my_reservations', 
  'My Reservations', 
  'Mes réservations', 
  'Meine Reservierungen',
  'ናይዚ ምዝገባታት',
  'Mis reservas',
  'حجوزاتي',
  'رزروهای من'
),
('reservation_cancelled_successfully', 
  'Reservation cancelled successfully', 
  'Réservation annulée avec succès', 
  'Reservierung erfolgreich storniert',
  'ምዝገባ ብኽብረት ተሰሪዙ',
  'Reserva cancelada exitosamente',
  'تم إلغاء الحجز بنجاح',
  'رزرو با موفقیت لغو شد'
),
('cancellation_failed', 
  'Cancellation failed', 
  'Échec de l/annulation', 
  'Stornierung fehlgeschlagen',
  'ምስራይ ምዝገባ ኣይተሳነን',
  'Cancelación fallida',
  'فشل الإلغاء',
  'لغو ناموفق بود'
),
('my_kitchen_reservations', 
  'My Kitchen Reservations', 
  'Mes réservations de cuisine', 
  'Meine Küchenreservierungen',
  'ናይ ክሽና ምዝገባታት',
  'Mis reservas de cocina',
  'حجوزات المطبخ الخاصة بي',
  'رزروهای آشپزخانه من'
),
('date', 
  'Date', 
  'Date', 
  'Datum',
  'ቀን',
  'Fecha',
  'التاريخ',
  'تاریخ'
),
('time_slot', 
  'Time Slot', 
  'Créneau horaire', 
  'Zeitfenster',
  'ናይ ግዜ ቦታ',
  'Franja horaria',
  'الفترة الزمنية',
  'بازه زمانی'
),
('confirm_cancel_reservation', 
  'Are you sure you want to cancel this reservation?', 
  'Êtes-vous sûr de vouloir annuler cette réservation ?', 
  'Sind Sie sicher, dass Sie diese Reservierung stornieren möchten?',
  'ርግጸኛ ኢኹም ነዚ ምዝገባ ክትሰርዩዶ?',
  '¿Está seguro de que desea cancelar esta reserva?',
  'هل أنت متأكد أنك تريد إلغاء هذا الحجز؟',
  'آیا مطمئن هستید که می خواهید این رزرو را لغو کنید؟'
),
('cancel', 
  'Cancel', 
  'Annuler', 
  'Abbrechen',
  'ሰርዝ',
  'Cancelar',
  'إلغاء',
  'لغو'
),
('no_reservations_yet', 
  'You have no reservations yet.', 
  'Vous n/avez pas encore de réservations.', 
  'Sie haben noch keine Reservierungen.',
  'ክሳብ ሕጂ ዝኾነ ምዝገባ የብልኩምን።',
  'Aún no tienes reservas.',
  'ليس لديك أي حجوزات حتى الآن.',
  'شما هنوز هیچ رزروی ندارید.'
),
('please_login_to_view_reservations', 
  'Please login to display the reservations.', 
  'Veuillez vous connecter pour afficher les réservations.', 
  'Bitte melden Sie sich an, um die Reservierungen anzuzeigen.',
  'በጃኹም ነቲ ምዝገባታት ንምርኣይ እቶ ግበሩ።',
  'Por favor inicie sesión para mostrar las reservas.',
  'يرجى تسجيل الدخول لعرض الحجوزات.',
  'لطفاً برای نمایش رزروها وارد شوید.'
),

/* reserve */
('kitchen_reservation_calendar', 
  'Kitchen Reservation Calendar', 
  'Calendrier de réservation de cuisine', 
  'Küchenreservierungskalender',
  'ካሌንዳር ምዝገባ ክሽና',
  'Calendario de reservas de cocina',
  'تقويم حجز المطبخ',
  'تقویم رزرو آشپزخانه'
),
('already_have_reservation_on_day', 
  'You already have a reservation on this day!', 
  'Vous avez déjà une réservation ce jour-là !', 
  'Sie haben an diesem Tag bereits eine Reservierung!',
  'ኣብዚ መዓልቲ ድሮ ምዝገባ ኣለኩም!',
  '¡Ya tienes una reserva en este día!',
  'لديك بالفعل حجز في هذا اليوم!',
  'شما در این روز از قبل رزرو دارید!'
),
('reservation_done_successfully', 
  'Reservation done successfully!', 
  'Réservation effectuée avec succès !', 
  'Reservierung erfolgreich durchgeführt!',
  'ምዝገባ ብኽብረት ተፈጢሩ!',
  '¡Reserva realizada con éxito!',
  'تم إجراء الحجز بنجاح!',
  'رزرو با موفقیت انجام شد!'
),
('error', 
  'Error', 
  'Erreur', 
  'Fehler',
  'ሓጋጊ',
  'Error',
  'خطأ',
  'خطا'
),
('reservation_limit_exceeded', 
  'You cannot reserve more than 4 times per week!', 
  'Vous ne pouvez pas réserver plus de 4 fois par semaine !', 
  'Sie können nicht mehr als 4 Mal pro Woche reservieren!',
  'ኣብ ሰሙን ካብ 4 ሳዕ ንላዕሊ ክትዝግብ ኣይትኽእልን!',
  '¡No puedes reservar más de 4 veces por semana!',
  'لا يمكنك الحجز أكثر من 4 مرات في الأسبوع!',
  'شما نمی‌توانید بیش از 4 بار در هفته رزرو کنید!'
),
('please_login_first', 
  'Please login first!', 
  'Veuillez vous connecter d/abord !', 
  'Bitte zuerst anmelden!',
  'በጃኹም በጃኹም መጀመርታ እቶ ግበሩ!',
  '¡Por favor inicie sesión primero!',
  'يرجى تسجيل الدخول أولاً!',
  'لطفاً ابتدا وارد شوید!'
),
('time', 
  'Time', 
  'Heure', 
  'Uhrzeit',
  'ግዜ',
  'Hora',
  'الوقت',
  'زمان'
),
('reserved', 
  'Reserved', 
  'Réservé', 
  'Reserviert',
  'ተዓዚብኩምዎ',
  'Reservado',
  'محجوز',
  'رزرو شده'
),
('confirm_reserve_time', 
  'Are you sure you want to reserve this time?', 
  'Êtes-vous sûr de vouloir réserver ce créneau ?', 
  'Sind Sie sicher, dass Sie diese Zeit reservieren möchten?',
  'ርግጸኛ ኢኹም ነዚ ግዜ ክትዓድዉዶ?',
  '¿Está seguro de que desea reservar este horario?',
  'هل أنت متأكد أنك تريد حجز هذا الوقت؟',
  'آیا مطمئن هستید که می خواهید این زمان را رزرو کنید؟'
),
('past', 
  'Past', 
  'Passé', 
  'Vergangenheit',
  'ሓለፈ',
  'Pasado',
  'الماضي',
  'گذشته'
),
('available', 
  'Available', 
  'Disponible', 
  'Verfügbar',
  'ተገዳስነት ዘለዎ',
  'Disponible',
  'متاح',
  'موجود'
),
('Monday', 
  'Monday', 
  'Lundi', 
  'Montag',
  'ሰኑይ',
  'Lunes',
  'الاثنين',
  'دوشنبه'
),
('Tuesday', 
  'Tuesday', 
  'Mardi', 
  'Dienstag',
  'ሠሉስ',
  'Martes',
  'الثلاثاء',
  'سه‌شنبه'
),
('Wednesday', 
  'Wednesday', 
  'Mercredi', 
  'Mittwoch',
  'ረቡዕ',
  'Miércoles',
  'الأربعاء',
  'چهارشنبه'
),
('Thursday', 
  'Thursday', 
  'Jeudi', 
  'Donnerstag',
  'ኃሙስ',
  'Jueves',
  'الخميس',
  'پنجشنبه'
),
('Friday', 
  'Friday', 
  'Vendredi', 
  'Freitag',
  'ዓርቢ',
  'Viernes',
  'الجمعة',
  'جمعه'
),
('Saturday', 
  'Saturday', 
  'Samedi', 
  'Samstag',
  'ቀዳም',
  'Sábado',
  'السبت',
  'شنبه'
),
('Sunday', 
  'Sunday', 
  'Dimanche', 
  'Sonntag',
  'ሰንበት',
  'Domingo',
  'الأحد',
  'یکشنبه'
),
('reserved_by', 
  'Reserved by', 
  'Réservé par', 
  'Reserviert durch',
  'ብተጠቃሚ ተዓዚብካ',
  'Reservado por',
  'محجوز بواسطة',
  'رزرو شده توسط'
),

/* users */
('users', 
  'Users', 
  'Utilisateurs', 
  'Benutzer',
  'ተጠቃሚታት',
  'Usuarios',
  'المستخدمون',
  'کاربران'
),
('registered_users', 
  'Registered Users', 
  'Utilisateurs enregistrés', 
  'Registrierte Benutzer',
  'ተመዝገብቲ ተጠቃሚታት',
  'Usuarios registrados',
  'المستخدمون المسجلون',
  'کاربران ثبت نام شده'
),
('user_id', 
  'User ID', 
  'ID utilisateur', 
  'Benutzer-ID',
  'ተጠቃሚ_ID',
  'ID de usuario',
  'معرف المستخدم',
  'شناسه کاربری'
),
('CNS_number', 
  'CNS Number', 
  'Numéro CNS', 
  'CNS-Nummer',
  'CNS ቑፅሪ',
  'Número CNS',
  'رقم CNS',
  'شماره CNS'
),
('role', 
  'Role', 
  'Rôle', 
  'Rolle',
  'ሓላፍነት',
  'Rol',
  'الدور',
  'نقش'
),
('changed_pass', 
  'Changed Pass', 
  'Mot de passe changé', 
  'Passwort geändert',
  'ተቐይሮ ዘሎ ፓስዎርድ',
  'Contraseña cambiada',
  'تم تغيير كلمة المرور',
  'رمز عبور تغییر کرده'
),
('action', 
  'Action', 
  'Action', 
  'Aktion',
  'ተግባር',
  'Acción',
  'إجراء',
  'عمل'
),
('delete', 
  'Delete', 
  'Supprimer', 
  'Löschen',
  'ሰርዝ',
  'Eliminar',
  'حذف',
  'حذف'
),
('true', 
  'True', 
  'vrai', 
  'wahr',
  'ሓቂ',
  'Verdadero',
  'صحيح',
  'درست'
),
('false', 
  'False', 
  'faux', 
  'falsch',
  'ሓሶት',
  'Falso',
  'خطأ',
  'نادرست'
),
('pending', 
  'Pending', 
  'En attente', 
  'Ausstehend',
  'ተጠቂሙ',
  'Pendiente',
  'قيد الانتظار',
  'در انتظار'
),
('active', 
  'Active', 
  'Actif', 
  'Aktiv',
  'ንጡፍ',
  'Activo',
  'نشط',
  'فعال'
),
('confirmation_either_to_activate_or_deactivate_user', 
  'Are you sure you want to activate or deactivate this user?', 
  'Êtes-vous sûr de vouloir activer ou désactiver cet utilisateur ?', 
  'Möchten Sie diesen Benutzer wirklich aktivieren oder deaktivieren?',
  'እቲ ተጠቃሚ ብምንቅስቓስ ወይ ብምሕዳም እንተ ትደሊ ሓረግ ዘለኻ?', 
  '¿Está seguro de que desea activar o desactivar a este usuario?', 
  'هل أنت متأكد أنك تريد تفعيل أو تعطيل هذا المستخدم؟', 
  'آیا مطمئن هستید که می‌خواهید این کاربر را فعال یا غیرفعال کنید؟'
),
('confirm_delete_user', 
  'Delete this user?', 
  'Supprimer cet utilisateur ?', 
  'Diesen Benutzer löschen?', 
  'እቲ ተጠቃሚ ምድምሳዕ ትደሊ?', 
  '¿Eliminar a este usuario?', 
  'هل تريد حذف هذا المستخدم؟', 
  'آیا می‌خواهید این کاربر را حذف کنید؟'
);